import type {
  Player,
  FormationPreset,
  SavedTacticalDiagram,
} from "../types/futsal";

export const INITIAL_PLAYERS: Player[] = [
  {
    id: "2",
    number: 2,
    name: "Huỳnh Tấn Phong",
    stamina: 8,
    attack: 7,
    defense: 7.5,
    positions: ["AL_R", "PI", "FI"],
    notes: "Dễ Cọc",
  },
  {
    id: "3",
    number: 3,
    name: "Mai Thanh",
    stamina: 6,
    attack: 7.5,
    defense: 6.5,
    positions: ["GK", "FI"],
    notes: "Dễ thiếu tập trung",
  },
  {
    id: "4",
    number: 4,
    name: "Ngô Thái Tuấn",
    stamina: 8.5,
    attack: 8.5,
    defense: 7.5,
    positions: ["GK", "AL_L", "PI", "FI"],
  },
  {
    id: "5",
    number: 5,
    name: "Nguyễn Bình An",
    stamina: 6.5,
    attack: 7,
    defense: 6.5,
    positions: ["PI", "AL_R"],
  },
  {
    id: "6",
    number: 6,
    name: "Nguyễn Cao Tấn",
    stamina: 7.5,
    attack: 9,
    defense: 6,
    positions: ["PI", "AL_L"],
    notes: "Dễ Tâm Lý",
  },
  {
    id: "7",
    number: 7,
    name: "Nguyen Minh Tan",
    stamina: null,
    attack: null,
    defense: null,
    positions: [],
  },
  {
    id: "9",
    number: 9,
    name: "Phạm Hữu Thành",
    stamina: 5,
    attack: 6,
    defense: 6,
    positions: ["GK", "FI", "AL_L"],
    notes: "Mau mệt",
  },
  {
    id: "10",
    number: 10,
    name: "Trần Hoàng Hiệp",
    stamina: 10,
    attack: 9,
    defense: 8,
    positions: ["AL_R"],
    notes: "Thể Lực Phi Thường",
  },
  {
    id: "11",
    number: 11,
    name: "Vo Hoang Ha",
    stamina: null,
    attack: null,
    defense: null,
    positions: ["AL_L", "PI"],
  },
  {
    id: "12",
    number: 12,
    name: "Vũ Đức Mạnh",
    stamina: 9,
    attack: null,
    defense: null,
    positions: ["PI"],
  },
  {
    id: "13",
    number: 13,
    name: "Vũ Trọng Phúc",
    stamina: 7.5,
    attack: 6,
    defense: 7,
    positions: ["GK", "FI"],
    notes: "666",
  },
  {
    id: "14",
    number: 14,
    name: "Vo Tien Phat",
    stamina: null,
    attack: null,
    defense: null,
    positions: ["PI", "AL_R"],
  },
];

export const FORMATION_PRESETS: FormationPreset[] = [
  {
    id: "4-0",
    name: "4-0",
    subName: "Xoay vòng",
    schema: "1-4-0 (Tứ giác xoay vòng)",
    positions: [
      { role: "GOALKEEPER", label: "THỦ MÔN (GOALKEEPER)", x: 10, y: 50 },
      { role: "FIXO", label: "HẬU VỆ TRÁI DƯỚI (FIXO LEFT)", x: 42, y: 25 },
      { role: "FIXO", label: "HẬU VỆ PHẢI DƯỚI (FIXO RIGHT)", x: 42, y: 75 },
      {
        role: "ALA_LEFT",
        label: "TIỀN VỆ CÁNH TRÁI TRÊN (ALA LEFT)",
        x: 75,
        y: 25,
      },
      {
        role: "ALA_RIGHT",
        label: "TIỀN VỆ CÁNH PHẢI TRÊN (ALA RIGHT)",
        x: 75,
        y: 75,
      },
    ],
  },
  {
    id: "3-1",
    name: "3-1",
    subName: "Pivot",
    schema: "1-3-1 (Kim Cương Pivot)",
    positions: [
      { role: "GOALKEEPER", label: "THỦ MÔN (GOALKEEPER)", x: 10, y: 50 },
      { role: "FIXO", label: "HẬU VỆ (FIXO)", x: 35, y: 50 },
      { role: "ALA_LEFT", label: "TIỀN VỆ CÁNH TRÁI (ALA LEFT)", x: 42, y: 22 },
      {
        role: "ALA_RIGHT",
        label: "TIỀN VỆ CÁNH PHẢI (ALA RIGHT)",
        x: 42,
        y: 78,
      },
      { role: "PIVOT", label: "TIỀN ĐẠO (PIVOT)", x: 82, y: 50 },
    ],
  },
  {
    id: "2-2",
    name: "2-2",
    subName: "Cân bằng",
    schema: "1-2-2 (Hình Vuông Cân Bằng)",
    positions: [
      { role: "GOALKEEPER", label: "THỦ MÔN (GOALKEEPER)", x: 10, y: 50 },
      { role: "FIXO", label: "HẬU VỆ TRÁI (FIXO LEFT)", x: 40, y: 30 },
      { role: "FIXO", label: "HẬU VỆ PHẢI (FIXO RIGHT)", x: 40, y: 70 },
      { role: "PIVOT", label: "TIỀN ĐẠO TRÁI (PIVOT LEFT)", x: 78, y: 30 },
      { role: "PIVOT", label: "TIỀN ĐẠO PHẢI (PIVOT RIGHT)", x: 78, y: 70 },
    ],
  },
  {
    id: "1-2-1",
    name: "1-2-1",
    subName: "Kim cương",
    schema: "1-2-1 (Hình Kim Cương)",
    positions: [
      { role: "GOALKEEPER", label: "THỦ MÔN (GOALKEEPER)", x: 10, y: 50 },
      { role: "FIXO", label: "HẬU VỆ (FIXO)", x: 28, y: 50 },
      { role: "ALA_LEFT", label: "TIỀN VỆ CÁNH TRÁI (ALA LEFT)", x: 50, y: 25 },
      {
        role: "ALA_RIGHT",
        label: "TIỀN VỆ CÁNH PHẢI (ALA RIGHT)",
        x: 50,
        y: 75,
      },
      { role: "PIVOT", label: "TIỀN ĐẠO (PIVOT)", x: 72, y: 50 },
    ],
  },
  {
    id: "1-3",
    name: "1-3",
    subName: "Tấn công",
    schema: "1-1-3 (Tam giác dâng cao)",
    positions: [
      { role: "GOALKEEPER", label: "THỦ MÔN (GOALKEEPER)", x: 10, y: 50 },
      { role: "FIXO", label: "HẬU VỆ (FIXO)", x: 35, y: 50 },
      { role: "ALA_LEFT", label: "TIỀN VỆ CÁNH TRÁI (ALA LEFT)", x: 72, y: 20 },
      {
        role: "ALA_RIGHT",
        label: "TIỀN VỆ CÁNH PHẢI (ALA RIGHT)",
        x: 72,
        y: 80,
      },
      { role: "PIVOT", label: "TIỀN ĐẠO (PIVOT)", x: 84, y: 50 },
    ],
  },
  {
    id: "0-4",
    name: "0-4",
    subName: "Power Play",
    schema: "0-4 (Power Play - Đặc biệt)",
    positions: [
      { role: "GOALKEEPER", label: "THỦ MÔN DÂNG (GOALKEEPER)", x: 22, y: 50 },
      { role: "FIXO", label: "HẬU VỆ DƯỚI (FIXO)", x: 55, y: 50 },
      { role: "ALA_LEFT", label: "TIỀN VỆ CÁNH TRÁI (ALA LEFT)", x: 80, y: 20 },
      {
        role: "ALA_RIGHT",
        label: "TIỀN VỆ CÁNH PHẢI (ALA RIGHT)",
        x: 80,
        y: 80,
      },
      { role: "PIVOT", label: "TIỀN ĐẠO (PIVOT)", x: 85, y: 50 },
    ],
  },
];

export const INITIAL_TACTICAL_SQUAD = {
  formationId: "1-3",
  slots: [
    {
      id: "slot-0",
      role: "GOALKEEPER" as const,
      label: "THỦ MÔN (GOALKEEPER)",
      x: 10,
      y: 50,
      playerId: "13",
      subPlayerIds: ["9"],
    },
    {
      id: "slot-1",
      role: "FIXO" as const,
      label: "HẬU VỆ (FIXO)",
      x: 35,
      y: 50,
      playerId: null,
      subPlayerIds: [],
    },
    {
      id: "slot-2",
      role: "ALA_LEFT" as const,
      label: "TIỀN VỆ CÁNH TRÁI (ALA LEFT)",
      x: 72,
      y: 20,
      playerId: "2",
      subPlayerIds: [],
    },
    {
      id: "slot-3",
      role: "ALA_RIGHT" as const,
      label: "TIỀN VỆ CÁNH PHẢI (ALA RIGHT)",
      x: 72,
      y: 80,
      playerId: "4",
      subPlayerIds: [],
    },
    {
      id: "slot-4",
      role: "PIVOT" as const,
      label: "TIỀN ĐẠO (PIVOT)",
      x: 84,
      y: 50,
      playerId: "6",
      subPlayerIds: [],
    },
  ],
  notes: "",
  attackDirection: "right" as const,
};

export const INITIAL_TACTICAL_DIAGRAMS: SavedTacticalDiagram[] = [
  {
    id: "1786610631847",
    name: "Chạy biên",
    shapes: [
      {
        id: "1",
        tool: "player-home",
        points: [{ x: 30, y: 70 }],
        color: "#16a34a",
        text: "Thái Tuấn",
        number: 4,
      },
      {
        id: "2",
        tool: "player-home",
        points: [{ x: 35, y: 35 }],
        color: "#16a34a",
        text: "Hữu Thành",
        number: 6,
      },
      {
        id: "3",
        tool: "player-home",
        points: [{ x: 75, y: 35 }],
        color: "#16a34a",
        text: "Cao Tấn",
        number: 9,
      },
      {
        id: "4",
        tool: "player-away",
        points: [{ x: 50, y: 35 }],
        color: "#dc2626",
        text: "Địch",
      },
      {
        id: "5",
        tool: "player-away",
        points: [{ x: 70, y: 40 }],
        color: "#dc2626",
        text: "Địch",
      },
      { id: "6", tool: "ball", points: [{ x: 30, y: 70 }], color: "#ffffff" },
      {
        id: "7",
        tool: "dashed-arrow",
        points: [
          { x: 30, y: 70 },
          { x: 75, y: 35 },
        ],
        color: "#facc15",
      },
      {
        id: "8",
        tool: "arrow",
        points: [
          { x: 30, y: 70 },
          { x: 55, y: 80 },
          { x: 80, y: 65 },
        ],
        color: "#ffffff",
      },
    ],
    updatedAt: "2026-08-13T08:43:58.349Z",
  },
  {
    id: "1786378593962",
    name: "Draft-001",
    shapes: [
      {
        id: "1",
        tool: "player-away",
        points: [{ x: 65, y: 25 }],
        color: "#dc2626",
        text: "Địch",
      },
      {
        id: "2",
        tool: "arrow",
        points: [
          { x: 65, y: 25 },
          { x: 40, y: 40 },
        ],
        color: "#ef4444",
      },
      {
        id: "3",
        tool: "player-home",
        points: [{ x: 40, y: 40 }],
        color: "#16a34a",
        text: "Thái Tuấn",
        number: 4,
      },
      {
        id: "4",
        tool: "player-home",
        points: [{ x: 25, y: 60 }],
        color: "#16a34a",
        text: "Tấn Phong",
        number: 2,
      },
      {
        id: "5",
        tool: "cross-red",
        points: [{ x: 50, y: 45 }],
        color: "#ef4444",
      },
      { id: "6", tool: "ball", points: [{ x: 65, y: 25 }], color: "#ffffff" },
    ],
    updatedAt: "2026-08-13T08:45:22.434Z",
  },
];
